apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-service
  labels:
    app: fibonacci-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibonacci-service
  template:
    metadata:
      labels:
        app: fibonacci-service
    spec:
      containers:
        - name: fibonacci-service
          image: fibonacci-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: REDIS_ADDRESS
              value: "redis:6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_DB
              value: "0"
            - name: MAX_N_TO_GENERATE
              value: "10000000"
            - name: CACHE_LOCK_TTL
              value: "1"
            - name: CACHE_JOB_TIMEOUT_MIN
              value: "20"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  labels:
    app: fibonacci-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fibonacci-service
